FROM apache/airflow:2.9.3-python3.11
ENV PYTHONPATH=/opt/airflow/include:/opt/airflow
USER airflow
COPY requirements-airflow.txt /requirements-airflow.txt
RUN pip install --no-cache-dir -r /requirements-airflow.txt
